apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
  name: flask-sentiment-analysis
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/flask-sentiment-analysis
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 2Gi
            cpu: 1000m
        env:
        - name: PORT
          value: "8080"
